version = 1

; Default, global settings for all models
[*]
flash-attn = on
n-gpu-layers = 99
cache-type-k = q8_0
cache-type-v = q8_0

[Qwen3.5-4B-Abliterated-Instruct-vision@Alice]
hf-repo = mradermacher/Qwen3.5-4B_Abliterated-i1-GGUF:IQ4_XS
mmproj-url = https://huggingface.co/mradermacher/Qwen3.5-4B_Abliterated-GGUF/resolve/main/Qwen3.5-4B_Abliterated.mmproj-Q8_0.gguf
ctx-size = 32768
temperature = 0.7
top-k = 20
top-p = 0.8
min-p = 0.0
presence-penalty = 1.5
repeat-penalty = 1.0
reasoning = off

[Qwen3.5-4B-Abliterated-Thinking-vision@Alice]
hf-repo = mradermacher/Qwen3.5-4B_Abliterated-i1-GGUF:IQ4_XS
mmproj-url = https://huggingface.co/mradermacher/Qwen3.5-4B_Abliterated-GGUF/resolve/main/Qwen3.5-4B_Abliterated.mmproj-Q8_0.gguf
ctx-size = 32768
temperature = 1.0
top-k = 20
top-p = 0.95
min-p = 0.0
presence-penalty = 1.5
repeat-penalty = 1.0
reasoning = on

[Qwen3.5-4B-PaperWitch-Heresy-Instruct-vision@Alice]
hf-repo = mradermacher/Qwen3.5-4B-PaperWitch-heresy-i1-GGUF:IQ4_XS
mmproj-url = https://huggingface.co/mradermacher/Qwen3.5-4B-PaperWitch-heresy-GGUF/resolve/main/Qwen3.5-4B-PaperWitch-heresy.mmproj-Q8_0.gguf
ctx-size = 32768
temperature = 0.7
top-k = 20
top-p = 0.8
min-p = 0.0
presence-penalty = 1.5
repeat-penalty = 1.0
reasoning = off

[Qwen3.5-4B-PaperWitch-Heresy-Thinking-vision@Alice]
hf-repo = mradermacher/Qwen3.5-4B-PaperWitch-heresy-i1-GGUF:IQ4_XS
mmproj-url = https://huggingface.co/mradermacher/Qwen3.5-4B-PaperWitch-heresy-GGUF/resolve/main/Qwen3.5-4B-PaperWitch-heresy.mmproj-Q8_0.gguf
ctx-size = 32768
temperature = 1.0
top-k = 20
top-p = 0.95
min-p = 0.0
presence-penalty = 1.5
repeat-penalty = 1.0
reasoning = on

[Crow-4B-Heretic-Instruct-vision@Alice]
hf-repo = mradermacher/Crow-4B-Opus-4.6-Distill-Heretic_Qwen3.5-i1-GGUF:IQ4_XS
mmproj-url = https://huggingface.co/mradermacher/Qwen3.5-4B-PaperWitch-heresy-GGUF/resolve/main/Qwen3.5-4B-PaperWitch-heresy.mmproj-Q8_0.gguf
ctx-size = 32768
temperature = 0.7
top-k = 20
top-p = 0.8
min-p = 0.0
presence-penalty = 1.5
repeat-penalty = 1.0
reasoning = off

[Crow-4B-Heretic-Thinking-vision@Alice]
hf-repo = mradermacher/Crow-4B-Opus-4.6-Distill-Heretic_Qwen3.5-i1-GGUF:IQ4_XS
mmproj-url = https://huggingface.co/mradermacher/Qwen3.5-4B-PaperWitch-heresy-GGUF/resolve/main/Qwen3.5-4B-PaperWitch-heresy.mmproj-Q8_0.gguf
ctx-size = 32768
temperature = 1.0
top-k = 20
top-p = 0.95
min-p = 0.0
presence-penalty = 1.5
repeat-penalty = 1.0
reasoning = on

[Nemotron-3-Nano-4B-Uncensored-Instruct]
hf-repo = HauhauCS/Nemotron3-Nano-4B-Uncensored-HauhauCS-Aggressive:IQ4_XS
ctx-size = 32768
temperature = 1.0
top-p = 0.95
reasoning = off

[Nemotron-3-Nano-4B-Uncensored-Thinking]
hf-repo = HauhauCS/Nemotron3-Nano-4B-Uncensored-HauhauCS-Aggressive:IQ4_XS
ctx-size = 32768
temperature = 1.0
top-p = 0.95
reasoning = on

[Qwen3-4B-Abliterated-Instruct@Alice]
hf-repo = mradermacher/Huihui-Qwen3-4B-abliterated-v2-i1-GGUF:IQ4_XS
ctx-size = 32768
temperature = 0.7
top-k = 20
top-p = 0.8
min-p = 0.0
reasoning = off

[Qwen3-4B-Abliterated-Thinking@Alice]
hf-repo = mradermacher/Huihui-Qwen3-4B-abliterated-v2-i1-GGUF:IQ4_XS
ctx-size = 32768
temperature = 0.6
top-k = 20
top-p = 0.95
min-p = 0.0
reasoning = on

[GLM-4.7-Flash-REAP-23B-A3B-heresy]
hf-repo = MuXodious/GLM-4.7-Flash-REAP-23B-A3B-absolute-heresy-GGUF:MXFP4_MOE
ctx-size = 16384
temperature = 1.0
top-p = 0.95
n-cpu-moe = 37
jinja = true

[Qwen2.5-Coder-1.5B-Abliterated@Alice]
hf-repo = bartowski/Qwen2.5-Coder-1.5B-Instruct-abliterated-GGUF:IQ4_XS
temperature = 0.7
top-k = 20
top-p = 0.8
repeat-penalty = 1.1

[Qwen3-Embedding-0.6B]
hf-repo = Qwen/Qwen3-Embedding-0.6B-GGUF:Q8_0
embedding = true

[Qwen3-Reranker-0.6B]
hf-repo = mradermacher/Qwen3-Reranker-0.6B-GGUF:Q8_0
temperature = 0.6
top-k = 20
top-p = 0.95
reranking = true
