version = 1

; Default, global settings for all models
[*]
flash-attn = auto

[Qwen3.5-4B-Abliterated-Instruct-vision@Alice]
hf-repo = mradermacher/Qwen3.5-4B_Abliterated-GGUF:IQ4_XS
n-gpu-layers = 24
temperature = 0.7
top-k = 20
top-p = 0.8
min-p = 0.0
presence-penalty = 1.5
repeat-penalty = 1.0
chat-template-kwargs = {"enable_thinking": false}

[Qwen3.5-4B-Abliterated-Thinking-vision@Alice]
hf-repo = mradermacher/Qwen3.5-4B_Abliterated-GGUF:IQ4_XS
n-gpu-layers = 24
temperature = 1.0
top-k = 20
top-p = 0.95
min-p = 0.0
presence-penalty = 1.5
repeat-penalty = 1.0
chat-template-kwargs = {"enable_thinking": true}

[Qwen2.5-Coder-1.5B-Abliterated@Alice]
hf-repo = bartowski/Qwen2.5-Coder-1.5B-Instruct-abliterated-GGUF:IQ4_XS
temperature = 0.7
top-k = 20
top-p = 0.8
repeat-penalty = 1.1

[Qwen3-Embedding-0.6B]
hf-repo = Qwen/Qwen3-Embedding-0.6B-GGUF:Q8_0
embedding = true

[Qwen3-Reranker-0.6B]
hf-repo = mradermacher/Qwen3-Reranker-0.6B-GGUF:Q8_0
reranking = true
