version = 1

; Default, global settings for all models
[*]
flash-attn = on
n-gpu-layers = all
cache-type-k = q8_0
cache-type-v = q8_0

; chat-template-file vendorised from: https://huggingface.co/google/gemma-4-E4B-it/raw/main/chat_template.jinja
[Gemma-4-E4B-vision]
hf-repo = mradermacher/gemma-4-E4B-it-ARA-heresy-i1-GGUF:IQ4_XS
mmproj-url = https://huggingface.co/mradermacher/gemma-4-E4B-it-ARA-heresy-GGUF/resolve/main/gemma-4-E4B-it-ARA-heresy.mmproj-Q8_0.gguf
chat-template-file = /Users/addianto/.config/llama.cpp/gemma-4-e4b-chat_template.jinja
ctx-size = 65536
temperature = 1.0
top-k = 64
top-p = 0.95
jinja = on
image-min-tokens=280
image-max-tokens=1120

[Qwen2.5-Coder-1.5B]
hf-repo = bartowski/Qwen2.5-Coder-1.5B-Instruct-abliterated-GGUF:Q6_K
temperature = 0.7
top-k = 20
top-p = 0.8
repeat-penalty = 1.1
reasoning = off
parallel = 1

[LiquidAI/LFM2.5-Embedding-350M]
hf-repo = LiquidAI/LFM2.5-Embedding-350M-GGUF
embedding = true
reasoning = off
parallel = 1

[Qwen3-Reranker-0.6B]
hf-repo = mradermacher/Qwen3-Reranker-0.6B-GGUF:Q8_0
reranking = true
temperature = 0.6
top-k = 20
top-p = 0.95
reasoning = off
parallel = 1
