---
name: Devstral Medium
version: 1.0.0
schema: v1

models:
  - name: Devstral Medium
    provider: mistral
    model: devstral-medium-2507
    apiKey: ${{ secrets.MISTRAL_API_KEY }}
    roles:
      - apply
      - chat
      - edit
