---
name: Mistral Medium
version: 1.0.0
schema: v1

models:
  - name: Mistral Medium
    provider: mistral
    model: mistral-medium-2508
    apiKey: ${{ secrets.MISTRAL_API_KEY }}
    roles:
      - apply
      - chat
      - edit