# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: 0.2.0
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Microsoft.PowerShell
      directives:
        description: Install PowerShell
        allowPrerelease: true
      settings:
        Id: Microsoft.PowerShell
        Source: winget
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Microsoft.WindowsTerminal
      dependsOn:
        - Microsoft.PowerShell
      directives:
        description: Install Windows Terminal
        allowPrerelease: true
      settings:
        Id: Microsoft.WindowsTerminal
        Source: winget
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: 7zip.7zip
      directives:
        description: Install 7-Zip
        allowPrerelease: true
      settings:
        Id: "7zip.7zip"
        Source: winget
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Git.Git
      directives:
        description: Install Git
        allowPrerelease: true
      settings:
        Id: Git.Git
        Source: winget
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Wilfred.difftastic
      directives:
        description: Install difftastic
        allowPrerelease: true
      settings:
        Id: Wilfred.difftastic
        Source: winget
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: koalaman.shellcheck
      directives:
        description: Install shellcheck
        allowPrerelease: true
      settings:
        Id: koalaman.shellcheck
        Source: winget
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: Docker.DockerDesktop
      directives:
        description: Install Docker Desktop
        allowPrerelease: true
      settings:
        Id: Docker.DockerDesktop
        Source: winget
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: kubernetes.kubectl
      directives:
        description: Install kubectl
        allowPrerelease: true
      settings:
        Id: kubernetes.kubectl
        Source: winget
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: SumatraPDF.SumatraPDF
      directives:
        description: Install SumatraPDF
        allowPrerelease: true
      settings:
        Id: SumatraPDF.SumatraPDF
        Source: winget
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: File-New-Project.EarTrumpet
      directives:
        description: Install EarTrumpet
        allowPrerelease: true
      settings:
        Id: File-New-Project.EarTrumpet
        Source: winget
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: dotPDN.PaintDotNet
      directives:
        description: Install Paint.NET
        allowPrerelease: true
      settings:
        Id: dotPDN.PaintDotNet
        Source: winget
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: LibreWolf.LibreWolf
      directives:
        description: Install LibreWolf
        allowPrerelease: true
      settings:
        Id: LibreWolf.LibreWolf
        Source: winget
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: MullvadVPN.MullvadBrowser
      directives:
        description: Install Mullvad Browser
        allowPrerelease: true
      settings:
        Id: MullvadVPN.MullvadBrowser
        Source: winget
        Ensure: Present
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: eloston.ungoogled-chromium
      directives:
        description: Install Ungoogled Chromium
        allowPrerelease: true
      settings:
        Id: eloston.ungoogled-chromium
        Source: winget
        Ensure: Present
