# yaml-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: "0.2.0"
  resources:
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: difftastic
      directives:
        description: Install difftastic
        allowPrerelease: false
      settings:
        id: Wilfred.difftastic
        source: winget
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: shellcheck
      directives:
        description: Install shellcheck
        allowPrerelease: false
      settings:
        id: koalaman.shellcheck
        source: winget
