# General settings

## Color support
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

## Enable mouse support
set -g mouse on

## Fix Vim escape key delay
set -sg escape-time 10

## Increase scrollback buffer size
set -g history-limit 50000

## Enable focus event
set -g focus-events on
