# My tmux configuration

## General
set -s escape-time 10                       # todo: what is this for?
set -sg repeat-time 600                     # todo: what is this for?
set -s focus-events on                      # todo: what is this for?

set -g prefix2 C-a                          # set secondary prefix key to Ctrl-A

set -g mouse on                             # enable mouse support
set -g history-limit 5000                   # increase scrollback history

## Display
set -g base-index 1                         # start window numbering from 1
setw -g pane-base-index 1                   # start pane numbering from 1 (to make it consistent with window)

set -g set-titles on                        # set terminal title
setw -g automatic-rename on                 # set window name to the current running program automatically
set -g renumber-windows on                  # renumber window automatically

# set -g default-terminal "tmux-256color"     # todo: what is this for?
# set -as terminal-features ",alacritty*:RGB" # enable 24-bit color support on terminal

## Compatibility
set -g prediction-dimming off               # fix glitch when running nvim under psmux?
